[SPARK-16459][SQL] Prevent dropping current database
This PR prevents dropping the current database to avoid errors like the followings.

```scala
scala> sql("create database delete_db")
scala> sql("use delete_db")
scala> sql("drop database delete_db")
scala> sql("create table t as select 1")
org.apache.spark.sql.catalyst.analysis.NoSuchDatabaseException: Database `delete_db` not found;
```

Pass the Jenkins tests including an updated testcase.

Author: Dongjoon Hyun <dongjoon@apache.org>

Closes #14115 from dongjoon-hyun/SPARK-16459.

(cherry picked from commit 7ac79da0e4607f7f89a3617edf53c2b174b378e8)
Signed-off-by: Herman van Hovell <hvanhovell@databricks.com>